export interface GlossaryTerm {
  id: string;
  zh: string;
  en: string;
  def_zh: string;
  def_en: string;
  site_id: string;
}

/** High-frequency field words. One plain definition + one place that shows it. */
export const GLOSSARY: GlossaryTerm[] = [
  {
    id: "danxia",
    zh: "丹霞",
    en: "Danxia",
    def_zh: "红层砂岩/砾岩被垂直节理切开、再崩成赤壁、巷谷和方山。模式产地在丹霞山。彩色丘陵若没有这套崩塌结构，不要叫丹霞。",
    def_en: "Red-bed sandstone or conglomerate cut by vertical joints, then collapsed into cliffs, alleyways and mesas. Type locality: Danxiashan. A colourful hill without that collapse sequence is not Danxia.",
    site_id: "danxiashan",
  },
  {
    id: "karst",
    zh: "喀斯特",
    en: "Karst",
    def_zh: "碳酸盐岩被水慢慢拆掉的地貌。灰岩、白云岩的鉴定留在室内，公园里不要滴酸。张家界石英砂岩柱不是喀斯特。",
    def_en: "Landforms made by water taking carbonate rock apart. Telling limestone from dolostone is an indoor job — do not acid-test in the park. Zhangjiajie’s quartz-sandstone pillars are not karst.",
    site_id: "shilin",
  },
  {
    id: "fenglin",
    zh: "峰林",
    en: "Fenglin",
    def_zh: "孤立的喀斯特峰立在溶蚀平原上，峰与峰之间是平地。桂林是教科书。北方河谷喀斯特不要叫峰林平原。",
    def_en: "Isolated karst peaks standing on a dissolution plain, with flat ground between them. Guilin is the textbook. Northern valley karst is not a fenglin plain.",
    site_id: "guilin-karst",
  },
  {
    id: "fengcong",
    zh: "峰丛",
    en: "Fengcong",
    def_zh: "喀斯特峰还连在一个基座上，谷底没溶成平原。兴文石海是这一类。峰林是峰已经孤立在平原上，例子在桂林。",
    def_en: "Karst peaks still sharing one base; the valley floor is not yet a dissolution plain. Xingwen is the example. Fenglin peaks already stand alone on a plain — Guilin.",
    site_id: "xingwen",
  },
  {
    id: "karren",
    zh: "石芽",
    en: "Karren",
    def_zh: "灰岩表面被雨水切出的沟槽和刃脊。石林是放大了的石芽网格。",
    def_en: "Grooves and blades cut into a limestone surface by rain. A stone forest is that grid, scaled up.",
    site_id: "shilin",
  },
  {
    id: "tiankeng",
    zh: "天坑",
    en: "Tiankeng",
    def_zh: "地下河顶板大规模塌出来的坑，围岩是碳酸盐岩。玛珥湖是爆炸坑，不要叫天坑。",
    def_en: "A pit from large-scale collapse of an underground-river roof, in carbonate rock. A maar is an explosion crater — not a tiankeng.",
    site_id: "leye-fengshan",
  },
  {
    id: "joint",
    zh: "节理",
    en: "Joint",
    def_zh: "岩石裂开但两盘没有明显错动的裂缝。垂直节理把丹霞和张家界切成墙和柱。",
    def_en: "A crack that opened without obvious slip. Vertical joints cut Danxia and Zhangjiajie into walls and pillars.",
    site_id: "zhangjiajie",
  },
  {
    id: "bedding",
    zh: "层理",
    en: "Bedding",
    def_zh: "沉积时一层一层叠上去的面。能指出一层的顶和底，才算看懂。",
    def_en: "The surfaces stacked as sediment was laid down. You have read it when you can point to the top and base of one bed.",
    site_id: "jixian",
  },
  {
    id: "unconformity",
    zh: "不整合",
    en: "Unconformity",
    def_zh: "上下两套岩层之间缺了一段时间，中间是剥蚀面。产状不同就是角度不整合。嵩山把好几道摊在一座山上。",
    def_en: "A gap in time between two rock packages, with an erosion surface in between. Different dips make an angular unconformity. Songshan stacks several on one mountain.",
    site_id: "songshan",
  },
  {
    id: "planation",
    zh: "夷平面",
    en: "Planation surface",
    def_zh: "被削平的古地面，后来抬升。张家界的方山顶、五台山的台顶，先是平的，再被切开。",
    def_en: "An old surface worn flat, then lifted. The mesa tops at Zhangjiajie and the flats of Wutai were level before they were cut.",
    site_id: "zhangjiajie",
  },
  {
    id: "spheroidal",
    zh: "球状风化",
    en: "Spheroidal weathering",
    def_zh: "花岗岩沿节理向里一层层剥，留下石蛋。不是火山弹。黄山、三清山常见。",
    def_en: "Granite peeling inward along joints, leaving tors. Not volcanic bombs. Common on Huangshan and Sanqingshan.",
    site_id: "huangshan",
  },
  {
    id: "columnar",
    zh: "柱状节理",
    en: "Columnar jointing",
    def_zh: "熔岩或熔结凝灰岩冷却收缩切出的多边形柱。香港酸性岩也能长，不一定是玄武岩。",
    def_en: "Polygonal columns from cooling contraction in lava or welded tuff. Hong Kong grew them in acid rock — not a basalt franchise.",
    site_id: "hongkong",
  },
  {
    id: "gssp",
    zh: "金钉子",
    en: "GSSP / Golden Spike",
    def_zh: "全球年代地层的标准点，钉在某一层。煤山一剖两钉：下面是 2005 年的长兴阶底（Clarkina wangi），上面是 2001 年的二叠–三叠系界线（Hindeodus parvus）。独立剖面，不属于常山世界地质公园。禁止取样。",
    def_en: "A point that defines a global time boundary. Meishan holds two spikes on one section: the base of the Changhsingian below (Clarkina wangi, ratified 2005) and the Permian–Triassic boundary above (Hindeodus parvus, ratified 2001). An independent section, not part of Changshan UNESCO Global Geopark. No sampling.",
    site_id: "meishan",
  },
  {
    id: "stratotype",
    zh: "层型",
    en: "Stratotype",
    def_zh: "定义某一套地层该长什么样的标准剖面。金钉子是全球界线层型；蓟县是华北中–新元古界的尺子。",
    def_en: "The section that defines what a unit should look like. A GSSP is a global boundary stratotype; Jixian is North China’s Meso–Neoproterozoic ruler.",
    site_id: "jixian",
  },
  {
    id: "redbed",
    zh: "红层",
    en: "Red beds",
    def_zh: "氧化铁染红的陆相砂砾岩。丹霞的原料，但红层不等于丹霞——还要有垂直节理和崩塌。",
    def_en: "Continental sandstone and conglomerate stained by iron oxide. The raw material of Danxia, but red beds are not Danxia until vertical joints and collapse have done their work.",
    site_id: "danxiashan",
  },
  {
    id: "dolostone",
    zh: "白云岩",
    en: "Dolostone",
    def_zh: "钙镁碳酸盐岩。和灰岩的差别留在室内认，露头上不要滴酸。房山石花洞、十渡钉在雾迷山组白云岩上。",
    def_en: "Calcium–magnesium carbonate. Tell it from limestone indoors — do not acid-test the outcrop. Fangshan’s Stone Flower Cave and Shidu sit on Wumishan dolostone.",
    site_id: "fangshan",
  },
  {
    id: "stromatolite",
    zh: "叠层石",
    en: "Stromatolite",
    def_zh: "微生物一层层堆出来的纹层石。凸起朝上指示顶。蓟县雾迷山组常见。禁止凿取。",
    def_en: "Laminated stone built by microbes. Convex-up marks the top. Common in the Wumishan at Jixian. Do not chisel.",
    site_id: "jixian",
  },
  {
    id: "maar",
    zh: "玛珥湖",
    en: "Maar",
    def_zh: "地下水遇上岩浆爆炸留下的圆坑，后来成湖。湖光岩是玛珥，不是喀斯特天坑。",
    def_en: "A round crater from groundwater meeting magma, later a lake. Huguangyan is a maar, not a karst tiankeng.",
    site_id: "huguangyan",
  },
  {
    id: "caldera",
    zh: "破火山口",
    en: "Caldera",
    def_zh: "岩浆房顶塌陷形成的大坑。长白山天池是破火山口湖，不是陨石坑，也不是堰塞湖。",
    def_en: "A large pit from collapse of a magma-chamber roof. Changbaishan’s Tianchi is a caldera lake — not a meteor crater and not a lava-dammed lake.",
    site_id: "changbaishan",
  },
  {
    id: "lookdonttake",
    zh: "只看不挖",
    en: "Look, don’t take",
    def_zh: "化石、矿物、标本：看、拍、记。不敲、不挖、不带走。中国古生物化石原则上属于国家。煤山这种层型点连灰岩碎屑也不许敲。",
    def_en: "Fossils, minerals, specimens: look, photograph, note. Do not hammer, dig, or take them home. Under Chinese law, fossils are in principle state property. At a golden spike such as Meishan, do not even chip the limestone.",
    site_id: "meishan",
  },
  {
    id: "colourhill",
    zh: "彩丘",
    en: "Colourful hills",
    def_zh: "干旱区河湖相地层的色带，风和间歇洪水切开软层。张掖是这一类。没有丹霞那套垂直节理和崩塌，不要叫丹霞。",
    def_en: "Colour bands in arid lake-and-river beds, cut by wind and flash floods. Zhangye is the case. Without Danxia’s vertical joints and collapse, it is not Danxia.",
    site_id: "zhangye",
  },
  {
    id: "yardang",
    zh: "雅丹",
    en: "Yardang",
    def_zh: "风顺着软弱夹层吹出的垄和槽。敦煌雅丹是风蚀。和张掖彩丘不是同一回事。",
    def_en: "Ridges and troughs blown out along weak beds. The Dunhuang yardang is wind erosion, not the same thing as Zhangye’s colourful hills.",
    site_id: "dunhuang",
  },
  {
    id: "dune",
    zh: "沙山",
    en: "Dune",
    def_zh: "风把沙堆上去。巴丹吉林的复合沙山是积出来的。雅丹是吹掉的。一个积，一个蚀。",
    def_en: "Wind piles sand up. The compound dunes of Badain Jaran are accumulation. A yardang is what wind removes. One is built; one is stripped.",
    site_id: "badain-jaran",
  },
  {
    id: "loess",
    zh: "黄土",
    en: "Loess",
    def_zh: "风吹来的粉砂。洛川把黄土和古土壤叠成一把尺子。不是红层，也不是丹霞。",
    def_en: "Silt carried by wind. Luochuan stacks loess and paleosols into a ruler. Not red beds, and not Danxia.",
    site_id: "luochuan",
  },
  {
    id: "qzpillar",
    zh: "石英砂岩峰林",
    en: "Quartz-sandstone pillars",
    def_zh: "张家界的柱是泥盆纪石英砂岩。夷平面被垂直节理切开。不是灰岩，不是喀斯特。不要在山上滴酸。",
    def_en: "Zhangjiajie’s pillars are Devonian quartz sandstone. A flat surface was cut by vertical joints. Not limestone, not karst. Do not acid-test them.",
    site_id: "zhangjiajie",
  },
  {
    id: "mesa",
    zh: "方山",
    en: "Mesa",
    def_zh: "顶是平的。丹霞里常是硬层留住了顶。张家界的平顶是夷平面剩下来的。先问岩石，再叫方山。",
    def_en: "A flat top. In Danxia a hard bed often holds the top. At Zhangjiajie the flat is a leftover planation surface. Ask what the rock is before you say mesa.",
    site_id: "danxiashan",
  },
  {
    id: "cave",
    zh: "溶洞",
    en: "Cave",
    def_zh: "长在碳酸盐岩里。石花洞是雾迷山组白云岩，石花是化学沉积，只看不摸。不要拿桂林峰林来套北方溶洞。",
    def_en: "A cave in carbonate rock. Shihuadong is Wumishan dolostone; the stone flowers are chemical deposits — look, don’t touch. Do not read a northern cave as Guilin fenglin.",
    site_id: "shihuadong",
  },
  {
    id: "knick",
    zh: "裂点",
    en: "Knickpoint",
    def_zh: "河床突然变陡的地方。壶口是黄河上的裂点，水在这里跌下去。不是天坑。",
    def_en: "A place where the riverbed suddenly steepens. Hukou is a knickpoint on the Yellow River — the water drops. Not a tiankeng.",
    site_id: "hukou",
  },
  {
    id: "meander",
    zh: "蛇曲",
    en: "Incised meander",
    def_zh: "河切进基岩还留着弯。永和的黄河蛇曲是河自己留下来的，不是人工渠。",
    def_en: "A river cut into bedrock that still keeps its bends. The Yonghe meanders of the Yellow River are the river’s own work, not a canal.",
    site_id: "yonghe",
  },
  {
    id: "delta",
    zh: "河口沙岛",
    en: "River-mouth island",
    def_zh: "河把泥沙送到口门，潮再把它塑成岛。崇明还在长。上海的国家地质公园在这里，不是佘山。",
    def_en: "A river delivers silt to its mouth; tides shape an island. Chongming is still growing. Shanghai’s national geopark is here, not at Sheshan.",
    site_id: "chongming",
  },
  {
    id: "waveplat",
    zh: "海蚀平台",
    en: "Wave-cut platform",
    def_zh: "浪把岸脚切平，留下一块潮间带的台。大连海岸能看。涨潮会改变还能走的范围，先看潮汐。",
    def_en: "Waves cut the foot of a shore flat, leaving a platform in the intertidal zone. The Dalian coast shows it. The tide changes where you can walk — check it first.",
    site_id: "dalian-coast",
  },
  {
    id: "eqlake",
    zh: "地震堰塞湖",
    en: "Earthquake-dammed lake",
    def_zh: "地震把山体震下来堵住溪流。重庆小南海是 1856 年那次，不是火山口，也不是十几万年前的湖。",
    def_en: "A quake dumps a slope into a stream and dams it. Xiaonanhai in Chongqing dates from 1856. Not a crater, and not a lake from a hundred-odd thousand years ago.",
    site_id: "xiaonanhai",
  },
  {
    id: "slidlake",
    zh: "滑坡堰塞",
    en: "Landslide dam",
    def_zh: "滑坡堵住河谷。易贡是这一类，2000 年溃决过。不是熔岩堰塞。",
    def_en: "A landslide blocks a valley. Yigong is one; it burst in 2000. Not a lava dam.",
    site_id: "yigong",
  },
  {
    id: "lavadam",
    zh: "熔岩堰塞",
    en: "Lava-dammed lake",
    def_zh: "熔岩流把河堵住。镜泊湖是玄武岩堵住牡丹江，湖是长条的。不是破火山口。",
    def_en: "A lava flow blocks a river. At Jingpohu, basalt dammed the Mudanjiang; the lake is elongate. Not a caldera.",
    site_id: "jingpohu",
  },
  {
    id: "glacier",
    zh: "冰川",
    en: "Glacier",
    def_zh: "冰在动，会刨出谷、留下冰碛。海螺沟是贡嘎山东坡的海洋性冰川。不是喀斯特。",
    def_en: "Moving ice cuts valleys and leaves moraine. Hailuogou is a maritime glacier on the east side of Gongga. Not karst.",
    site_id: "hailuogou",
  },
  {
    id: "horn",
    zh: "角峰",
    en: "Horn",
    def_zh: "几条冰川从不同方向刨一座山，留下尖顶。四姑娘山的角峰是这么来的。山体是花岗岩，不是丹霞。",
    def_en: "Glaciers cutting a mountain from several sides leave a sharp peak. That is how the horns of Siguniang formed. The rock is granite, not Danxia.",
    site_id: "siguniang",
  },
  {
    id: "impact",
    zh: "撞击坑",
    en: "Impact crater",
    def_zh: "陨石撞出来的坑，要有冲击证据才算数。白沙在本站按名录上的「陨石坑」收录。撞击是否成立、国家级是否还在现行名录里，没有再对原文复核。",
    def_en: "A crater needs shock evidence before it is an impact. Baisha is listed here under the name on the roll. Whether the impact is established, and whether it is still on the current national list, has not been re-checked against the source.",
    site_id: "baisha-crater",
  },
  {
    id: "granite",
    zh: "花岗岩",
    en: "Granite",
    def_zh: "在地下慢慢冷的酸性岩浆岩，颗粒粗，石英和长石看得清。黄山是这一类，不是火山锥。",
    def_en: "An acid magma that cooled slowly underground. Coarse grains; quartz and feldspar you can see. Huangshan is this, not a volcanic cone.",
    site_id: "huangshan",
  },
  {
    id: "rhyolite",
    zh: "流纹岩",
    en: "Rhyolite",
    def_zh: "喷出地表的酸性岩浆岩，可以有流纹。雁荡山是白垩纪流纹岩和凝灰岩，不是花岗岩名山。",
    def_en: "Acid magma erupted at the surface; it can show flow bands. Yandangshan is Cretaceous rhyolite and tuff, not a granite mountain.",
    site_id: "yandangshan",
  },
  {
    id: "basalt",
    zh: "玄武岩",
    en: "Basalt",
    def_zh: "喷出的基性岩浆岩，一般颜色深。五大连池是新生代玄武岩。西樵山不是这一类。",
    def_en: "A basic lava, usually dark. Wudalianchi is Cenozoic basalt. Xiqiao is not.",
    site_id: "wudalianchi",
  },
  {
    id: "trachyte",
    zh: "粗面岩",
    en: "Trachyte",
    def_zh: "偏碱性的喷出岩。西樵山是粗面岩穹丘，不是玄武岩，也不是夏威夷式绳状熔岩。",
    def_en: "A mildly alkaline volcanic rock. Xiqiao is a trachyte dome — not basalt, and not Hawaiian rope lava.",
    site_id: "xiqiaoshan",
  },
  {
    id: "neck",
    zh: "火山颈",
    en: "Volcanic neck",
    def_zh: "管道里的岩浆冷了，围岩被剥掉，脖子留着。右玉是火山颈群。不是活火山。",
    def_en: "Magma cooled in the pipe; the country rock wore away and the neck stayed. Youyu is a group of necks. Not a live volcano.",
    site_id: "youyu",
  },
  {
    id: "tuff",
    zh: "凝灰岩",
    en: "Tuff",
    def_zh: "火山碎屑固结成的岩。佘山有流纹质到粗面质的凝灰岩，不是花岗岩。",
    def_en: "Volcanic debris welded or cemented into rock. Sheshan has rhyolitic to trachytic tuff, not granite.",
    site_id: "sheshan",
  },
  {
    id: "limestone",
    zh: "灰岩",
    en: "Limestone",
    def_zh: "碳酸盐岩里方解石为主的那一类。石林是灰岩被溶出来的。和白云岩怎么分，留在室内，公园里不要滴酸。",
    def_en: "The carbonate rock that is mostly calcite. The Shilin stone forest is dissolved limestone. Telling it from dolostone stays indoors — do not acid-test in the park.",
    site_id: "shilin",
  },
  {
    id: "conglomerate",
    zh: "砾岩",
    en: "Conglomerate",
    def_zh: "砾石被胶结在一起。丹霞红层里常有。摸到的是砾，不是花岗岩的斑晶。",
    def_en: "Pebbles cemented together. Common in Danxia red beds. What you feel is a pebble, not a granite phenocryst.",
    site_id: "danxiashan",
  },
  {
    id: "shale",
    zh: "页岩",
    en: "Shale",
    def_zh: "薄、容易沿层裂开的泥质岩。王家湾的笔石印在页岩上。不要掰走。",
    def_en: "Thin mudstone that splits along the beds. Graptolites at Wangjiawan are printed on shale. Do not flake a piece off.",
    site_id: "gssp-wangjiawan",
  },
  {
    id: "phenocryst",
    zh: "斑晶",
    en: "Phenocryst",
    def_zh: "细基质里较大的晶体。佘山浅色火山岩里可以找。石蛋是球状风化，不是一颗斑晶。",
    def_en: "A larger crystal in a finer groundmass. Look for them in Sheshan’s pale volcanic rock. A tor is spheroidal weathering, not one big phenocryst.",
    site_id: "sheshan",
  },
  {
    id: "ropelava",
    zh: "绳状熔岩",
    en: "Rope lava",
    def_zh: "玄武岩流表面拧成绳子的样子。五大连池可以看。西樵山是粗面岩穹丘，不要说成夏威夷式绳状熔岩。",
    def_en: "The surface of a basalt flow twisted into ropes. Wudalianchi is a place to see it. Xiqiao is a trachyte dome — do not call it Hawaiian rope lava.",
    site_id: "wudalianchi",
  },
  {
    id: "fault",
    zh: "断层",
    en: "Fault",
    def_zh: "岩层断开，两盘有错动。节理是裂开但没有明显错动。龙门山是逆冲带，汶川地震的发震断裂在这一带。不稳定的坡上不要自己去找露头。",
    def_en: "The rock broke and the two sides slipped. A joint opened without obvious slip. Longmenshan is a thrust belt; the fault of the Wenchuan earthquake is in this range. Do not hunt outcrops on an unstable slope.",
    site_id: "longmenshan",
  },
  {
    id: "crossbed",
    zh: "交错层理",
    en: "Cross-bedding",
    def_zh: "一层里面斜着的纹层，记下当时的水流或风。红层砂岩里常见。只看，不要挖。",
    def_en: "Inclined laminae inside a bed. They record the water current or the wind. Common in red-bed sandstone. Look only — do not dig.",
    site_id: "danxiashan",
  },
  {
    id: "conodont",
    zh: "牙形石",
    en: "Conodont",
    def_zh: "毫米级的微体化石，现场看不见个体。煤山两颗钉子都用牙形石：下面 Clarkina wangi（2005），上面 Hindeodus parvus（2001）。",
    def_en: "Millimetre-scale microfossils. You will not see an individual in the field. Both Meishan spikes use conodonts: Clarkina wangi below (2005), Hindeodus parvus above (2001).",
    site_id: "meishan",
  },
  {
    id: "trilobite",
    zh: "三叶虫",
    en: "Trilobite",
    def_zh: "已经灭绝的节肢动物，印在层面上。排碧阶的金钉子是球接子 Glyptagnostus reticulatus，不是牙形石。只看，不抠。",
    def_en: "An extinct arthropod, printed on a bedding surface. The Paibi golden spike is the agnostoid Glyptagnostus reticulatus, not a conodont. Look. Do not pick at the bed.",
    site_id: "gssp-paibi",
  },
  {
    id: "graptolite",
    zh: "笔石",
    en: "Graptolite",
    def_zh: "像压扁的锯条，印在页岩上。黄泥塘的达瑞威尔阶金钉子看的是笔石。不要掰页岩。",
    def_en: "Like a flattened saw-blade, printed on shale. The Darriwilian golden spike at Huangnitang is read from graptolites. Do not split the shale off.",
    site_id: "gssp-huangnitang",
  },
  {
    id: "lager",
    zh: "特异埋藏",
    en: "Lagerstätte",
    def_zh: "软的身体也保下来的化石层。澄江动物群是寒武纪的这一类。属于国家，不能敲。",
    def_en: "A fossil bed that also kept the soft parts. The Chengjiang fauna is a Cambrian one. It belongs to the state. Do not hammer.",
    site_id: "chengjiang",
  },
  {
    id: "extinction",
    zh: "大灭绝",
    en: "Mass extinction",
    def_zh: "二叠纪末的大灭绝写在煤山剖面上部那条界线附近。标志是 Hindeodus parvus，钉子 2001 年钉下。它和下面 2005 年的长兴阶底不是同一层。",
    def_en: "The end-Permian extinction is written near the upper boundary at Meishan. The marker is Hindeodus parvus; the spike was ratified in 2001. It is not the same bed as the 2005 base of the Changhsingian below.",
    site_id: "meishan",
  },
  {
    id: "ordohigh",
    zh: "高处的海相地层",
    en: "Marine beds, now high",
    def_zh: "珠峰附近有奥陶纪的海相地层。山是后来挤上去的，不是奥陶纪就有今天的高度。",
    def_en: "Ordovician marine beds sit near Everest. The mountain was squeezed up later. It was not this high in the Ordovician.",
    site_id: "everest-ordovician",
  },
  {
    id: "dinosaur",
    zh: "恐龙化石",
    en: "Dinosaur bone",
    def_zh: "自贡大山铺的恐龙在侏罗纪砂岩里。看展陈和层位。不挖，不带走。",
    def_en: "The Dashanpu dinosaurs at Zigong lie in Jurassic sandstone. Read the display and the bed. Do not dig, and do not take a piece.",
    site_id: "zigong",
  },
  {
    id: "marine",
    zh: "海生爬行动物",
    en: "Marine reptile",
    def_zh: "关岭的化石层是三叠纪的海生爬行动物。不是恐龙那一层。只看不挖。",
    def_en: "The Guanling beds are Triassic marine reptiles. Not the dinosaur beds. Look, don’t dig.",
    site_id: "guanling",
  },
  {
    id: "coords",
    zh: "坐标",
    en: "Coordinates",
    def_zh: "库存是 WGS84。大陆中文地图显示前会换成国测局坐标。图上的点是园区或观景台，不是可以去敲的采样坐标。",
    def_en: "Stored coordinates are WGS84. The Chinese mainland map shifts them to GCJ-02 before display. A pin is a park or a viewpoint, not a place you are invited to sample.",
    site_id: "hongkong",
  },
  {
    id: "urban",
    zh: "城市地质遗迹",
    en: "Urban geosite",
    def_zh: "长在城里或城边的石头。佘山是上海的火山残丘。上海的国家地质公园是崇明岛，不是佘山。",
    def_en: "Rock in or beside a city. Sheshan is Shanghai’s volcanic remnant. Shanghai’s national geopark is Chongming Island, not Sheshan.",
    site_id: "sheshan",
  },
  {
    id: "worldpark",
    zh: "世界地质公园",
    en: "UNESCO Global Geopark",
    def_zh: "联合国教科文组织的一张名录，和国家地质公园不是同一张表。黄山两张表上都有。有国家地质公园不是世界地质公园。",
    def_en: "A UNESCO list, not the same list as China’s national geoparks. Huangshan is on both. A national geopark is not automatically a UNESCO Global Geopark.",
    site_id: "huangshan",
  },
  {
    id: "iugs",
    zh: "IUGS 地质遗产",
    en: "IUGS geoheritage",
    def_zh: "国际地质科学联合会的另一张名单。不等于世界地质公园，也不等于国家地质公园。本站只保留核对过的几处，石林是其中之一。",
    def_en: "A separate list from the International Union of Geological Sciences. Not a UNESCO Global Geopark, and not a national geopark. This site keeps only the entries that were checked. Shilin is one of them.",
    site_id: "shilin",
  },
];

export function glossaryById(id: string): GlossaryTerm | undefined {
  return GLOSSARY.find((t) => t.id === id);
}

export function termsForLocale(locale: "zh" | "en"): { id: string; word: string }[] {
  return GLOSSARY.map((t) => ({ id: t.id, word: locale === "en" ? t.en : t.zh })).sort(
    (a, b) => b.word.length - a.word.length,
  );
}
