/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AskRouteImport } from './routes/ask'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as EnRouteImport } from './routes/en'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as NearbyRouteImport } from './routes/nearby'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as CardIdRouteImport } from './routes/card.$id'
import { Route as GsspIndexRouteImport } from './routes/gssp.index'
import { Route as GsspIdRouteImport } from './routes/gssp.$id'
import { Route as RoutesIndexRouteImport } from './routes/routes.index'
import { Route as RoutesIdRouteImport } from './routes/routes.$id'
import { Route as SitesIndexRouteImport } from './routes/sites.index'
import { Route as SitesIdRouteImport } from './routes/sites.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyRoute = NearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const CardIdRoute = CardIdRouteImport.update({
  id: '/card/$id',
  path: '/card/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GsspIndexRoute = GsspIndexRouteImport.update({
  id: '/gssp/',
  path: '/gssp/',
  getParentRoute: () => rootRouteImport,
} as any)
const GsspIdRoute = GsspIdRouteImport.update({
  id: '/gssp/$id',
  path: '/gssp/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIndexRoute = RoutesIndexRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIdRoute = RoutesIdRouteImport.update({
  id: '/routes/$id',
  path: '/routes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesIndexRoute = SitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesIdRoute = SitesIdRouteImport.update({
  id: '/sites/$id',
  path: '/sites/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ask': typeof AskRoute
  '/browse': typeof BrowseRoute
  '/catalog': typeof CatalogRoute
  '/compare': typeof CompareRoute
  '/en': typeof EnRoute
  '/glossary': typeof GlossaryRoute
  '/nearby': typeof NearbyRoute
  '/offline': typeof OfflineRoute
  '/card/$id': typeof CardIdRoute
  '/gssp/$id': typeof GsspIdRoute
  '/routes/$id': typeof RoutesIdRoute
  '/sites/$id': typeof SitesIdRoute
  '/gssp/': typeof GsspIndexRoute
  '/routes/': typeof RoutesIndexRoute
  '/sites/': typeof SitesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ask': typeof AskRoute
  '/browse': typeof BrowseRoute
  '/catalog': typeof CatalogRoute
  '/compare': typeof CompareRoute
  '/en': typeof EnRoute
  '/glossary': typeof GlossaryRoute
  '/nearby': typeof NearbyRoute
  '/offline': typeof OfflineRoute
  '/card/$id': typeof CardIdRoute
  '/gssp/$id': typeof GsspIdRoute
  '/routes/$id': typeof RoutesIdRoute
  '/sites/$id': typeof SitesIdRoute
  '/gssp': typeof GsspIndexRoute
  '/routes': typeof RoutesIndexRoute
  '/sites': typeof SitesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ask': typeof AskRoute
  '/browse': typeof BrowseRoute
  '/catalog': typeof CatalogRoute
  '/compare': typeof CompareRoute
  '/en': typeof EnRoute
  '/glossary': typeof GlossaryRoute
  '/nearby': typeof NearbyRoute
  '/offline': typeof OfflineRoute
  '/card/$id': typeof CardIdRoute
  '/gssp/$id': typeof GsspIdRoute
  '/routes/$id': typeof RoutesIdRoute
  '/sites/$id': typeof SitesIdRoute
  '/gssp/': typeof GsspIndexRoute
  '/routes/': typeof RoutesIndexRoute
  '/sites/': typeof SitesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ask'
    | '/browse'
    | '/catalog'
    | '/compare'
    | '/en'
    | '/glossary'
    | '/nearby'
    | '/offline'
    | '/card/$id'
    | '/gssp/$id'
    | '/routes/$id'
    | '/sites/$id'
    | '/gssp/'
    | '/routes/'
    | '/sites/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ask'
    | '/browse'
    | '/catalog'
    | '/compare'
    | '/en'
    | '/glossary'
    | '/nearby'
    | '/offline'
    | '/card/$id'
    | '/gssp/$id'
    | '/routes/$id'
    | '/sites/$id'
    | '/gssp'
    | '/routes'
    | '/sites'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ask'
    | '/browse'
    | '/catalog'
    | '/compare'
    | '/en'
    | '/glossary'
    | '/nearby'
    | '/offline'
    | '/card/$id'
    | '/gssp/$id'
    | '/routes/$id'
    | '/sites/$id'
    | '/gssp/'
    | '/routes/'
    | '/sites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AskRoute: typeof AskRoute
  BrowseRoute: typeof BrowseRoute
  CatalogRoute: typeof CatalogRoute
  CompareRoute: typeof CompareRoute
  EnRoute: typeof EnRoute
  GlossaryRoute: typeof GlossaryRoute
  NearbyRoute: typeof NearbyRoute
  OfflineRoute: typeof OfflineRoute
  CardIdRoute: typeof CardIdRoute
  GsspIdRoute: typeof GsspIdRoute
  RoutesIdRoute: typeof RoutesIdRoute
  SitesIdRoute: typeof SitesIdRoute
  GsspIndexRoute: typeof GsspIndexRoute
  RoutesIndexRoute: typeof RoutesIndexRoute
  SitesIndexRoute: typeof SitesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby': {
      id: '/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof NearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/$id': {
      id: '/card/$id'
      path: '/card/$id'
      fullPath: '/card/$id'
      preLoaderRoute: typeof CardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gssp/': {
      id: '/gssp/'
      path: '/gssp'
      fullPath: '/gssp/'
      preLoaderRoute: typeof GsspIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gssp/$id': {
      id: '/gssp/$id'
      path: '/gssp/$id'
      fullPath: '/gssp/$id'
      preLoaderRoute: typeof GsspIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/': {
      id: '/routes/'
      path: '/routes'
      fullPath: '/routes/'
      preLoaderRoute: typeof RoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$id': {
      id: '/routes/$id'
      path: '/routes/$id'
      fullPath: '/routes/$id'
      preLoaderRoute: typeof RoutesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/': {
      id: '/sites/'
      path: '/sites'
      fullPath: '/sites/'
      preLoaderRoute: typeof SitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$id': {
      id: '/sites/$id'
      path: '/sites/$id'
      fullPath: '/sites/$id'
      preLoaderRoute: typeof SitesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AskRoute: AskRoute,
  BrowseRoute: BrowseRoute,
  CatalogRoute: CatalogRoute,
  CompareRoute: CompareRoute,
  EnRoute: EnRoute,
  GlossaryRoute: GlossaryRoute,
  NearbyRoute: NearbyRoute,
  OfflineRoute: OfflineRoute,
  CardIdRoute: CardIdRoute,
  GsspIdRoute: GsspIdRoute,
  RoutesIdRoute: RoutesIdRoute,
  SitesIdRoute: SitesIdRoute,
  GsspIndexRoute: GsspIndexRoute,
  RoutesIndexRoute: RoutesIndexRoute,
  SitesIndexRoute: SitesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
